[package]
name = "bptree-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
concread = "0.5.0"
getrandom = { version = "0.2", features = ["js"] }
js-sys = "0.3.69"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"

[lib]
crate-type = ["cdylib"]

[dependencies.wasm-bindgen]
version = "0.2"
features = ["serde-serialize"]
