name: CI
on: [push, workflow_dispatch]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run @canvas-js/okra tests
        run: npm run test --workspace=@canvas-js/okra

  test-build:
    name: Missing dependencies between subpackages (pnpm)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 22.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Install modules
        run: pnpm i

      - name: Build
        run: pnpm run build
